"""'Observaciones'

Revision ID: a39a6ad73000
Revises: fe48b26b69e3
Create Date: 2016-08-04 08:32:24.819716

"""

# revision identifiers, used by Alembic.
revision = 'a39a6ad73000'
down_revision = 'fe48b26b69e3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('spatial_ref_sys')
    op.add_column('participantes', sa.Column('observaciones', sa.Text(), nullable=True))
    op.add_column('victimas', sa.Column('causa', sa.String(length=20), nullable=True))
    op.add_column('victimas', sa.Column('observaciones', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('victimas', 'observaciones')
    op.drop_column('victimas', 'causa')
    op.drop_column('participantes', 'observaciones')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    ### end Alembic commands ###
